# Generated by Django 5.2.10 on 2026-01-16 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_group_grouppermission_usergroup'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupPermission',
            new_name='Group_Permissions',
        ),
        migrations.RenameModel(
            old_name='UserGroup',
            new_name='User_Groups',
        ),
    ]
